# Generated by Django 5.1.7 on 2025-03-26 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cuisine_type", models.CharField(max_length=100)),
                ("food_base", models.CharField(max_length=100)),
                ("taste", models.CharField(max_length=100)),
                ("dietary_type", models.CharField(max_length=100)),
                ("last_meal", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_foodrequest",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FoodResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("RECIPE", "레시피"),
                            ("HEALTH", "건강"),
                            ("FOOD", "음식"),
                        ],
                        max_length=8,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_foodresult",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RecipeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ingredients", models.JSONField(blank=True, default=list)),
                ("serving_size", models.IntegerField(blank=True, null=True)),
                ("cooking_time", models.IntegerField(blank=True, null=True)),
                ("difficulty", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_reciperequest",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserHealthRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("exercise_frequency", models.CharField(max_length=100)),
                (
                    "allergies",
                    models.JSONField(blank=True, default=list, verbose_name="알레르기"),
                ),
                ("disliked_foods", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_userhealthrequest",
                "ordering": ("-created_at",),
            },
        ),
    ]
