# Generated by Django 5.1.7 on 2025-03-13 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("recipe", "레시피 추천"),
                            ("meal_plan", "식단 추천"),
                            ("food_recommendation", "음식 추천"),
                        ],
                        max_length=30,
                        verbose_name="요청 유형",
                    ),
                ),
                ("request_data", models.JSONField(verbose_name="요청 데이터")),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="응답 데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 요청",
                "verbose_name_plural": "AI 요청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100, verbose_name="음식명")),
                (
                    "food_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="음식 종류"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "nutritional_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="영양 정보"
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(blank=True, verbose_name="추천 이유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recommendations",
                        to="ai.airequest",
                        verbose_name="AI 요청",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "음식 추천 결과",
                "verbose_name_plural": "음식 추천 결과",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="몸무게 (kg)",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("diet", "다이어트"),
                            ("bulk_up", "벌크업"),
                            ("maintenance", "유지어트"),
                        ],
                        default="maintenance",
                        max_length=20,
                        verbose_name="목표",
                    ),
                ),
                (
                    "exercise_frequency",
                    models.CharField(
                        choices=[
                            ("none", "운동 안함"),
                            ("light", "가벼운 운동 (주 1-2회)"),
                            ("moderate", "중간 강도 운동 (주 3-4회)"),
                            ("active", "활발한 운동 (주 5-6회)"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="운동 빈도",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(blank=True, default=list, verbose_name="알레르기"),
                ),
                (
                    "disliked_foods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="비선호 음식"
                    ),
                ),
                (
                    "goal_start_date",
                    models.DateField(blank=True, null=True, verbose_name="목표 시작일"),
                ),
                (
                    "goal_end_date",
                    models.DateField(blank=True, null=True, verbose_name="목표 종료일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 건강 프로필",
                "verbose_name_plural": "사용자 건강 프로필",
            },
        ),
    ]
