# Generated by Django 5.1.7 on 2025-03-18 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFoodRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "음식 추천"),
                            ("health", "건강 기반 추천"),
                            ("recipe", "레시피 추천"),
                        ],
                        max_length=30,
                        verbose_name="요청 유형",
                    ),
                ),
                ("request_data", models.JSONField(verbose_name="요청 데이터")),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="응답 데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 요청",
                "verbose_name_plural": "AI 요청 목록",
                "db_table": "AIFoodRequest",
            },
        ),
        migrations.CreateModel(
            name="AIFoodResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "음식 추천"),
                            ("health", "건강 기반 추천"),
                            ("recipe", "레시피 추천"),
                        ],
                        max_length=30,
                        verbose_name="요청 타입 유형",
                    ),
                ),
                ("food_name", models.CharField(max_length=100, verbose_name="음식명")),
                (
                    "food_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="음식 종류"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "nutritional_info",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="영양 정보"
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(blank=True, verbose_name="추천 이유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 추천 결과",
                "verbose_name_plural": "AI 추천 결과 목록",
                "db_table": "AIFoodResult",
            },
        ),
        migrations.CreateModel(
            name="AIRecipeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="레시피 이름")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "음식 추천"),
                            ("health", "건강 기반 추천"),
                            ("recipe", "레시피 추천"),
                        ],
                        max_length=30,
                        verbose_name="요청 유형",
                    ),
                ),
                ("description", models.TextField(verbose_name="레시피 설명")),
                ("preparation_time", models.IntegerField(verbose_name="준비 시간(분)")),
                ("cooking_time", models.IntegerField(verbose_name="조리 시간(분)")),
                ("serving_size", models.IntegerField(verbose_name="제공 인원")),
                ("difficulty", models.CharField(max_length=20, verbose_name="난이도")),
                (
                    "cuisine_type",
                    models.CharField(
                        max_length=50, verbose_name="요리 종류(한식/중식 등)"
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        max_length=50, verbose_name="식사 종류(아침/점심/저녁)"
                    ),
                ),
                ("ingredients", models.JSONField(verbose_name="필요 재료 목록")),
                ("instructions", models.JSONField(verbose_name="조리 순서")),
                (
                    "nutrition_info",
                    models.JSONField(blank=True, null=True, verbose_name="영양 정보"),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="AI 생성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aifoodrequest",
                        verbose_name="관련 AI 요청 ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 레시피 요청",
                "verbose_name_plural": "AI 레시피 요청 목록",
                "db_table": "AIRecipeRequest",
            },
        ),
        migrations.CreateModel(
            name="AIUserHealthRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("food", "음식 추천"),
                            ("health", "건강 기반 추천"),
                            ("recipe", "레시피 추천"),
                        ],
                        max_length=30,
                        verbose_name="요청 타입 유형",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="몸무게 (kg)",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("gain_muscle", "근육량 증가"),
                            ("diet", "다이어트"),
                            ("maintenance", "유지"),
                        ],
                        default="maintenance",
                        max_length=20,
                        verbose_name="목표",
                    ),
                ),
                (
                    "exercise_frequency",
                    models.CharField(
                        choices=[
                            ("none", "운동안함"),
                            ("once", "주1회"),
                            ("two_to_three", "주2~3회"),
                            ("four_to_five", "주4~5회"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="운동 빈도",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(blank=True, default=list, verbose_name="알레르기"),
                ),
                (
                    "disliked_foods",
                    models.JSONField(
                        blank=True, default=list, verbose_name="비선호 음식"
                    ),
                ),
                (
                    "goal_start_date",
                    models.DateField(blank=True, null=True, verbose_name="목표 시작일"),
                ),
                (
                    "goal_end_date",
                    models.DateField(blank=True, null=True, verbose_name="목표 종료일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 사용자 건강 요청",
                "verbose_name_plural": "AI 사용자 건강 요청 목록",
                "db_table": "AIUserHealthRequest",
            },
        ),
    ]
