# Generated by Django 5.1.7 on 2025-03-13 05:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Meal Log ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meal_name", models.CharField(help_text="음식명", max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, help_text="음식 설명", null=True),
                ),
                ("meal_time", models.DateTimeField(help_text="식사 시간")),
                ("meal_type", models.CharField(help_text="식사 종류", max_length=50)),
                (
                    "nutrition_info",
                    models.JSONField(blank=True, help_text="영양 정보", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="사용자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meal_log",
                "ordering": ["meal_time"],
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="User Goal ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("DIET", "다이어트"),
                            ("MUSCLE_GAIN", "근육량 증가"),
                            ("BALANCED_NUTRITION", "균형잡힌 식단"),
                        ],
                        help_text="목표 선정(DIET, MUSCLE_GAIN, BALANCED_NUTRITION)",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="목표 설명", null=True),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, help_text="목표 시작일"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="목표 마감일", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="진행중 여부"),
                ),
                (
                    "goal_metrics",
                    models.JSONField(
                        blank=True, help_text="구체적 목표 설정", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="업데이트 시간"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="사용자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_goal",
                "ordering": ["-created_at"],
            },
        ),
    ]
