# Generated by Django 5.1.7 on 2025-03-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="report",
            new_name="report_repo_user_id_c947f1_idx",
            old_name="report_user_id_ef95fe_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="report_repo_status_7d0999_idx",
            old_name="report_status_74972f_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="report_repo_type_cc67d0_idx",
            old_name="report_type_9eba38_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="report_repo_created_be46cb_idx",
            old_name="report_created_2a12c2_idx",
        ),
        migrations.AlterModelTable(
            name="report",
            table=None,
        ),
    ]
