# Generated by Django 5.1.7 on 2025-03-26 16:48


import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="로그 ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "로그인"),
                            ("LOGOUT", "로그아웃"),
                            ("UPDATE_PROFILE", "프로필 업데이트"),
                            ("DELETE_PROFILE", "프로필 삭제"),
                            ("VIEW_REPORT", "리포트 조회"),
                            ("CREATE_REPORT", "리포트 생성"),
                            ("DELETE_REPORT", "리포트 삭제"),
                            ("UPDATE_REPORT", "리포트 수정"),
                        ],
                        help_text="로그액션",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="사용자 IP", unpack_ipv4=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, help_text="추가 정보", null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="사용자 ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "log_activitylog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="log_activit_user_id_fb88fa_idx"
                    ),
                    models.Index(
                        fields=["action"], name="log_activit_action_a83aa8_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="log_activit_created_e7bb46_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="log_activit_ip_addr_a290b7_idx"
                    ),
                ],
            },
        ),
    ]
