# Generated by Django 5.1.7 on 2025-03-24 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="log_activit_user_id_fb88fa_idx",
            old_name="activity_lo_user_id_f9e1c8_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="log_activit_action_a83aa8_idx",
            old_name="activity_lo_action_f14761_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="log_activit_created_e7bb46_idx",
            old_name="activity_lo_created_8906e2_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="log_activit_ip_addr_a290b7_idx",
            old_name="activity_lo_ip_addr_866d60_idx",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                help_text="사용자 ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="activitylog",
            table=None,
        ),
    ]
