# Generated by Django 5.1.7 on 2025-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "로그인"),
                    ("LOGOUT", "로그아웃"),
                    ("UPDATE_PROFILE", "프로필 업데이트"),
                    ("DELETE_PROFILE", "프로필 삭제"),
                    ("VIEW_REPORT", "리포트 조회"),
                    ("CREATE_REPORT", "리포트 생성"),
                    ("DELETE_REPORT", "리포트 삭제"),
                    ("UPDATE_REPORT", "리포트 수정"),
                    ("FOOD_REQUEST", "AI 음식 추천"),
                    ("RECIPE_REQUEST", "AI 음식 레시피 추천"),
                    ("HELATH_REQUEST", "AI 건강 식단 추천"),
                ],
                help_text="로그액션",
                max_length=255,
            ),
        ),
    ]
