name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - release  # release 브랜치에 push하면 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hak2881/ai-service-backend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Main-pj-AI-Service
            git pull origin release   # 깃에서 최신 docker-compose.yml 등 가져오기
            docker pull hak2881/ai-service-backend:latest
            docker-compose down
            docker-compose up -d